version: '3.8'
services:
  db:
    image: mariadb
    container_name: algafood_mariadb
    environment:
        MYSQL_ROOT_PASSWORD: root
        TZ: America/Sao_Paulo
    ports:
    - "3306:3306"
    volumes:
    - algafood_data:/var/lib/mysql

volumes:
  algafood_data:
